#lang info

;; One Dark Colors.
(define black        #(40 44 52))
(define white        #(187 187 187))
(define light-gray   #(92 99 112))
(define dark-gray    #(51 56 66))
(define red          #(224 107 116))
(define green        #(152 195 121))
(define light-yellow #(229 192 123))
(define dark-yellow  #(209 154 102))
(define blue         #(97 175 239))
(define magenta      #(198 120 221))
(define cyan         #(85 182 194))
  
;; One Dark Scheme.
(define framework:color-schemes
  `(#hash((name . "One Dark")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:error-background-highlighting                       ,red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,green)
            (drracket:syncheck:matching-identifiers                       ,dark-gray)
            (framework:basic-canvas-background                            ,black)
            (framework:default-text-color                                 ,white)
            (framework:line-numbers                                       ,light-gray)
            (framework:line-numbers-current-line-number-background        ,black)
            (framework:line-numbers-current-line-number-foreground        ,black)
            (framework:line-numbers-when-word-wrapping                    ,black)
            (framework:misspelled-text-color                              ,white)
            (framework:paren-match-color                                  ,dark-gray)
            (framework:program-contour-current-location-bar               ,dark-gray)
            (drracket:check-syntax:both-obligation-style-pref             ,light-yellow)
            (drracket:check-syntax:free-variable                          ,red)
            (drracket:check-syntax:imported                               ,magenta)
            (drracket:check-syntax:lexically-bound                        ,cyan)
            (drracket:check-syntax:my-obligation-style-pref               ,red)
            (drracket:check-syntax:set!d                                  ,red)
            (drracket:check-syntax:their-obligation-style-pref            ,green)
            (drracket:check-syntax:unk-obligation-style-pref              ,white)
            (drracket:check-syntax:unused-require                         ,red)
            (drracket:read-eval-print-loop:error-color                    ,red)
            (drracket:read-eval-print-loop:out-color                      ,green)
            (drracket:read-eval-print-loop:value-color                    ,blue)
            (framework:syntax-color:scheme:comment                        ,light-gray)
            (framework:syntax-color:scheme:constant                       ,dark-yellow)
            (framework:syntax-color:scheme:error                          ,red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,dark-yellow)
            (framework:syntax-color:scheme:keyword                        ,magenta)
            (framework:syntax-color:scheme:other                          ,white)
            (framework:syntax-color:scheme:parenthesis                    ,white)
            (framework:syntax-color:scheme:string                         ,green)
            (framework:syntax-color:scheme:symbol                         ,blue)
            (framework:syntax-color:scheme:text                           ,green)
            (plt:htdp:test-coverage-off                                   ,red)
            (plt:htdp:test-coverage-on                                    ,white)
            (plt:module-language:test-coverage-off                        ,red)
            (plt:module-language:test-coverage-on                         ,white))))))